package server;

public enum PacketType {
    LOGIN,REGISTER,ADD_DISCOUNT_REQUEST,EDIT_DISCOUNT_REQUEST,REMOVE_DISCOUNT_REQUEST,
    ADD_PRODUCT_FROM_STOCK,ADD_NEW_PRODUCT,ACCEPT_REQUEST,DECLINE_REQUEST,INCREASE_COUNT_CART,DECREASE_COUNT_CART,ADD_CATEGORY,EDIT_CATEGORY,
    REMOVE_CATEGORY, GET_PERSON, IS_FIRST_MANAGER_REGISTERED, LOG_OUT, GET_PERSON_TYPE,GET_BANK_TOKEN, GET_BANK_BALANCE,
    GET_TRANSACTION
}
